export const data = JSON.parse("{\"key\":\"v-646bda3d\",\"path\":\"/guide/self/%E5%86%99%E4%BD%9C.html\",\"title\":\"📕 写作\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"📕 写作\",\"icon\":null,\"description\":\"吴军阅读与写作讲义 《吴军阅读与写作讲义 (https://book.douban.com/subject/35426741/)》的前半部分涵盖了很多实用技巧，帮助我澄清了对听、说、读、写的认识。而后半部分则是一些阅读范例，类似于语文书中的阅读理解，我准备将其当作工具书，等待无聊时慢慢阅读。 部分记录： 在古希腊，奴隶也接受教育，但是他们所学的是谋生技...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/guide/self/%E5%86%99%E4%BD%9C.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"十里桃夭\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"📕 写作\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"吴军阅读与写作讲义 《吴军阅读与写作讲义 (https://book.douban.com/subject/35426741/)》的前半部分涵盖了很多实用技巧，帮助我澄清了对听、说、读、写的认识。而后半部分则是一些阅读范例，类似于语文书中的阅读理解，我准备将其当作工具书，等待无聊时慢慢阅读。 部分记录： 在古希腊，奴隶也接受教育，但是他们所学的是谋生技...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Hon\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"📕 写作\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Hon\\\",\\\"url\\\":\\\"http://www.hon.ink\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"吴军阅读与写作讲义\",\"slug\":\"吴军阅读与写作讲义\",\"link\":\"#吴军阅读与写作讲义\",\"children\":[]},{\"level\":2,\"title\":\"故事：材质、结构、风格和银幕剧作的原理\",\"slug\":\"故事-材质、结构、风格和银幕剧作的原理\",\"link\":\"#故事-材质、结构、风格和银幕剧作的原理\",\"children\":[]},{\"level\":2,\"title\":\"一本小小的红色写作书\",\"slug\":\"一本小小的红色写作书\",\"link\":\"#一本小小的红色写作书\",\"children\":[]}],\"readingTime\":{\"minutes\":2.28,\"words\":683},\"filePathRelative\":\"guide/self/写作.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
