export const data = JSON.parse("{\"key\":\"v-311f90b9\",\"path\":\"/guide/self/%E6%8F%90%E5%8D%87%E6%80%9D%E7%BB%B4.html\",\"title\":\"📕 提升思维\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"📕 提升思维\",\"icon\":null,\"description\":\"成长的边界 《成长的边界 (https://book.douban.com/subject/35410754/)》是探索更多的可能性，从外部视角审视自己。 尝试新的活动、建立新的网络、寻找新的榜样——来发现这些可能性。; 不要纠结于执行细节，从外部视角去审视项目。多从其他案例来类比，这样更容易理解，也可以检查自己的项目是否靠谱。; 公正 P56：遵守传...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/guide/self/%E6%8F%90%E5%8D%87%E6%80%9D%E7%BB%B4.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"十里桃夭\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"📕 提升思维\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"成长的边界 《成长的边界 (https://book.douban.com/subject/35410754/)》是探索更多的可能性，从外部视角审视自己。 尝试新的活动、建立新的网络、寻找新的榜样——来发现这些可能性。; 不要纠结于执行细节，从外部视角去审视项目。多从其他案例来类比，这样更容易理解，也可以检查自己的项目是否靠谱。; 公正 P56：遵守传...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Hon\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"📕 提升思维\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Hon\\\",\\\"url\\\":\\\"http://www.hon.ink\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"成长的边界\",\"slug\":\"成长的边界\",\"link\":\"#成长的边界\",\"children\":[]},{\"level\":2,\"title\":\"福格行为模型\",\"slug\":\"福格行为模型\",\"link\":\"#福格行为模型\",\"children\":[]},{\"level\":2,\"title\":\"The 5 AM Club\",\"slug\":\"the-5-am-club\",\"link\":\"#the-5-am-club\",\"children\":[]},{\"level\":2,\"title\":\"这就是 OKR\",\"slug\":\"这就是-okr\",\"link\":\"#这就是-okr\",\"children\":[]}],\"readingTime\":{\"minutes\":2.25,\"words\":674},\"filePathRelative\":\"guide/self/提升思维.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
