export const data = JSON.parse("{\"key\":\"v-7dfb9d4b\",\"path\":\"/note/guide/shehui/%E5%A4%A7%E7%A7%A6%E5%B8%9D%E5%9B%BD.html\",\"title\":\"大秦帝国读后感\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"大秦帝国读后感\",\"icon\":\"editor\",\"order\":5,\"description\":\"时间 从2022年8月开始阅读《大秦帝国》开始到今天2023年2月结束，总时间近5个月，算是断断续续的读完了一个大概。不自量力的来写个读后感，本文只是个人的见解。 大秦帝国君主交替结构图\\r 如有不对，还请指正 为什么是秦朝统一华夏 1. 战略：自秦孝公开始任用商鞅变法初始，到秦庄襄王都在积极或不干涉法制的进程，中间虽然经历过一些波折但总体的大方向均是要...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/note/guide/shehui/%E5%A4%A7%E7%A7%A6%E5%B8%9D%E5%9B%BD.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"十里桃夭\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"大秦帝国读后感\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"时间 从2022年8月开始阅读《大秦帝国》开始到今天2023年2月结束，总时间近5个月，算是断断续续的读完了一个大概。不自量力的来写个读后感，本文只是个人的见解。 大秦帝国君主交替结构图\\r 如有不对，还请指正 为什么是秦朝统一华夏 1. 战略：自秦孝公开始任用商鞅变法初始，到秦庄襄王都在积极或不干涉法制的进程，中间虽然经历过一些波折但总体的大方向均是要...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Hon\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"大秦帝国读后感\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Hon\\\",\\\"url\\\":\\\"http://www.hon.ink\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"时间\",\"slug\":\"时间\",\"link\":\"#时间\",\"children\":[]},{\"level\":2,\"title\":\"大秦帝国君主交替结构图\",\"slug\":\"大秦帝国君主交替结构图\",\"link\":\"#大秦帝国君主交替结构图\",\"children\":[]},{\"level\":2,\"title\":\"为什么是秦朝统一华夏\",\"slug\":\"为什么是秦朝统一华夏\",\"link\":\"#为什么是秦朝统一华夏\",\"children\":[]},{\"level\":2,\"title\":\"为什么七国均不用儒学\",\"slug\":\"为什么七国均不用儒学\",\"link\":\"#为什么七国均不用儒学\",\"children\":[{\"level\":3,\"title\":\"焚书坑儒？\",\"slug\":\"焚书坑儒\",\"link\":\"#焚书坑儒\",\"children\":[]},{\"level\":3,\"title\":\"我所认为的儒学\",\"slug\":\"我所认为的儒学\",\"link\":\"#我所认为的儒学\",\"children\":[]}]},{\"level\":2,\"title\":\"秦朝做了什么\",\"slug\":\"秦朝做了什么\",\"link\":\"#秦朝做了什么\",\"children\":[{\"level\":3,\"title\":\"政治\",\"slug\":\"政治\",\"link\":\"#政治\",\"children\":[]},{\"level\":3,\"title\":\"经济\",\"slug\":\"经济\",\"link\":\"#经济\",\"children\":[]},{\"level\":3,\"title\":\"军事\",\"slug\":\"军事\",\"link\":\"#军事\",\"children\":[]},{\"level\":3,\"title\":\"这些对后世有什么影响\",\"slug\":\"这些对后世有什么影响\",\"link\":\"#这些对后世有什么影响\",\"children\":[]}]},{\"level\":2,\"title\":\"美句欣赏\",\"slug\":\"美句欣赏\",\"link\":\"#美句欣赏\",\"children\":[]},{\"level\":2,\"title\":\"One More Thing\",\"slug\":\"one-more-thing\",\"link\":\"#one-more-thing\",\"children\":[]}],\"readingTime\":{\"minutes\":11.67,\"words\":3501},\"filePathRelative\":\"note/guide/shehui/大秦帝国.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
