export const data = JSON.parse("{\"key\":\"v-05c50683\",\"path\":\"/guide/psychology/%E5%BD%B1%E5%93%8D%E5%8A%9B.html\",\"title\":\"📗 影响力\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"📗 影响力\",\"icon\":null,\"description\":\"《影响力 (https://book.douban.com/subject/1786387/)》让其他人按你的想法行为。 固定行为模式 当我们请别人帮忙时，如果能够讲出一个理由，那我们得到别人帮助的可能性就更大。原因很简单，人们就是喜欢为自己所做的事找一个理由。 对比原理 对比原理会影响我们对前后两件事情之间的差异的判断。简单地说，如果两件东西很不一样...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/guide/psychology/%E5%BD%B1%E5%93%8D%E5%8A%9B.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"十里桃夭\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"📗 影响力\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"《影响力 (https://book.douban.com/subject/1786387/)》让其他人按你的想法行为。 固定行为模式 当我们请别人帮忙时，如果能够讲出一个理由，那我们得到别人帮助的可能性就更大。原因很简单，人们就是喜欢为自己所做的事找一个理由。 对比原理 对比原理会影响我们对前后两件事情之间的差异的判断。简单地说，如果两件东西很不一样...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Hon\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"📗 影响力\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Hon\\\",\\\"url\\\":\\\"http://www.hon.ink\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"固定行为模式\",\"slug\":\"固定行为模式\",\"link\":\"#固定行为模式\",\"children\":[]},{\"level\":2,\"title\":\"对比原理\",\"slug\":\"对比原理\",\"link\":\"#对比原理\",\"children\":[]},{\"level\":2,\"title\":\"互惠原理\",\"slug\":\"互惠原理\",\"link\":\"#互惠原理\",\"children\":[]},{\"level\":2,\"title\":\"拒绝—退让\",\"slug\":\"拒绝—退让\",\"link\":\"#拒绝—退让\",\"children\":[]},{\"level\":2,\"title\":\"承诺和一致\",\"slug\":\"承诺和一致\",\"link\":\"#承诺和一致\",\"children\":[]}],\"readingTime\":{\"minutes\":8.82,\"words\":2646},\"filePathRelative\":\"guide/psychology/影响力.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
