export const data = JSON.parse("{\"key\":\"v-7a9fcd72\",\"path\":\"/guide/%E5%BF%83%E7%90%86%E5%AD%A6/%E8%87%AA%E6%88%91%E8%AE%A4%E7%9F%A5.html\",\"title\":\"📗 自我认知\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"📗 自我认知\",\"icon\":null,\"description\":\"人性的弱点 《人性的弱点 (https://book.douban.com/subject/25985683/)》的副标题是如何赢取友谊与影响他人。 不应该看到优点，而是要看到对方的需求、心里缺失。; 代入感、共鸣：连问自己三次为什么，找到对方真实的原因。挖掘深层次精神需求，作为开场。; 刺激性言语：让对方想吐槽，想反馈。没心眼>真诚。例：一不小心一眼...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/guide/%E5%BF%83%E7%90%86%E5%AD%A6/%E8%87%AA%E6%88%91%E8%AE%A4%E7%9F%A5.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"十里桃夭\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"📗 自我认知\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"人性的弱点 《人性的弱点 (https://book.douban.com/subject/25985683/)》的副标题是如何赢取友谊与影响他人。 不应该看到优点，而是要看到对方的需求、心里缺失。; 代入感、共鸣：连问自己三次为什么，找到对方真实的原因。挖掘深层次精神需求，作为开场。; 刺激性言语：让对方想吐槽，想反馈。没心眼>真诚。例：一不小心一眼...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Hon\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"📗 自我认知\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Hon\\\",\\\"url\\\":\\\"http://www.hon.ink\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"人性的弱点\",\"slug\":\"人性的弱点\",\"link\":\"#人性的弱点\",\"children\":[]},{\"level\":2,\"title\":\"了不起的我\",\"slug\":\"了不起的我\",\"link\":\"#了不起的我\",\"children\":[]},{\"level\":2,\"title\":\"拖延心理学\",\"slug\":\"拖延心理学\",\"link\":\"#拖延心理学\",\"children\":[]}],\"readingTime\":{\"minutes\":2.81,\"words\":843},\"filePathRelative\":\"guide/心理学/自我认知.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
